spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pitech-blog?createDatabaseIfNotExist=true
    username: root
#    TODO: CHANGE WITH root BEFORE DOCKER
    password: Hooligan1995
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
server:
  port: 8080
  servlet:
    context-path: "/api/pitech-blog"
  error:
    include-message: always
security:
  issuer: "https://www.pitech-blog.com/"
  secret: "Dsed#CLhQ@%FC7Kt58pjhZVgwa^^xr*f0HdpCkdAEC3^yEtwS@u*ox8@4FN!"
  expiration: 3600000
  prefix: "Bearer "
springdoc:
  swagger-ui:
    path: "/swagger-ui.html"
validation:
  type:
    not-null: "NOT_NULL"
    min: "MIN"
    max: "MAX"
    regex: "REGEX"
    min-uppercase-letters: "MIN_UPPERCASE_LETTERS"
    min-lowercase-letters: "MIN_LOWERCASE_LETTERS"
    min-digits: "MIN_DIGITS"
    min-special-characters: "MIN_SPECIAL_CHARACTERS"