spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pitech-blog?createDatabaseIfNotExist=true
    username: root
#    TODO: CHANGE WITH root BEFORE DOCKER
    password: Hooligan1995
  jpa:
    hibernate:
#      ddl-auto: create-drop
#      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
#  TODO: REMOVE AFTER DEPLOY
#  TESTING
#  mail:
#    host: "sandbox.smtp.mailtrap.io"
#    port: 25
#    username: "b9fe37ebcb1b58"
#    password: "0790e2174a00d3"
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#  DEVELOPMENT
  mail:
    host: "smtp.gmail.com"
    port: 587
    username: "edoardofilippo.borrello@gmail.com"
    password: "mkfjqizkqszumlbt"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 8080
  servlet:
    context-path: "/api/pitech-blog"
  error:
    include-message: always
security:
  issuer: "https://www.pitech-blog.com/"
  secret: "Dsed#CLhQ@%FC7Kt58pjhZVgwa^^xr*f0HdpCkdAEC3^yEtwS@u*ox8@4FN!"
  expiration: 3600000
#  TESTING
#  expiration: 10000
  prefix: "Bearer "
springdoc:
  swagger-ui:
    path: "/swagger-ui.html"
validation:
  type:
    not-null: "notNull"
    not-empty: "notEmpty"
    min: "min"
    max: "max"
    regex: "regex"
    min-uppercase-letters: "minUppercaseLetters"
    min-lowercase-letters: "minLowercaseLetters"
    min-digits: "minDigits"
    min-special-characters: "minSpecialCharacters"