package it.itj.academy.blogbe.util.db_filler;

import it.itj.academy.blogbe.entity.Tag;
import it.itj.academy.blogbe.repository.CategoryRepository;
import it.itj.academy.blogbe.repository.TagRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Component;

import java.util.List;
import java.util.Set;

@RequiredArgsConstructor
@Component
public class TagFiller {
    private final TagRepository tagRepository;
    private final CategoryRepository categoryRepository;

    public void fillTags() {
        tagRepository.deleteAll(tagRepository.findAll());
        Set<Tag> tags = Set.of(
            new Tag("Indie", List.of(categoryRepository.findByName("Music").get(), categoryRepository.findByName("Gaming").get())),
            new Tag("Rock", List.of(categoryRepository.findByName("Music").get())),
            new Tag("Pop", List.of(categoryRepository.findByName("Music").get())),
            new Tag("Hip Hop", List.of(categoryRepository.findByName("Music").get())),
            new Tag("Rap", List.of(categoryRepository.findByName("Music").get())),
            new Tag("R&B", List.of(categoryRepository.findByName("Music").get())),
            new Tag("Metal", List.of(categoryRepository.findByName("Music").get())),
            new Tag("Jazz", List.of(categoryRepository.findByName("Music").get())),
            new Tag("Blues", List.of(categoryRepository.findByName("Music").get())),
            new Tag("Folk", List.of(categoryRepository.findByName("Music").get())),
            new Tag("Country", List.of(categoryRepository.findByName("Music").get())),
            new Tag("Classical", List.of(categoryRepository.findByName("Music").get())),
            new Tag("Reggae", List.of(categoryRepository.findByName("Music").get())),
            new Tag("Soul", List.of(categoryRepository.findByName("Music").get())),
            new Tag("Techno", List.of(categoryRepository.findByName("Music").get())),
            new Tag("House", List.of(categoryRepository.findByName("Music").get())),
            new Tag("Trance", List.of(categoryRepository.findByName("Music").get())),
            new Tag("Dubstep", List.of(categoryRepository.findByName("Music").get())),
            new Tag("Drum and Bass", List.of(categoryRepository.findByName("Music").get())),
            new Tag("Hardcore", List.of(categoryRepository.findByName("Music").get())),
            new Tag("Dance", List.of(categoryRepository.findByName("Music").get())),
            new Tag("Electro", List.of(categoryRepository.findByName("Music").get())),
            new Tag("Disco", List.of(categoryRepository.findByName("Music").get())),
            new Tag("Funk", List.of(categoryRepository.findByName("Music").get())),
            new Tag("Grunge", List.of(categoryRepository.findByName("Music").get())),
            new Tag("Punk", List.of(categoryRepository.findByName("Music").get())),
            new Tag("PS5", List.of(categoryRepository.findByName("Gaming").get())),
            new Tag("PS4", List.of(categoryRepository.findByName("Gaming").get())),
            new Tag("PS3", List.of(categoryRepository.findByName("Gaming").get())),
            new Tag("PS2", List.of(categoryRepository.findByName("Gaming").get())),
            new Tag("PS1", List.of(categoryRepository.findByName("Gaming").get())),
            new Tag("Xbox Series X", List.of(categoryRepository.findByName("Gaming").get())),
            new Tag("Xbox Series S", List.of(categoryRepository.findByName("Gaming").get())),
            new Tag("Xbox One", List.of(categoryRepository.findByName("Gaming").get())),
            new Tag("Xbox 360", List.of(categoryRepository.findByName("Gaming").get())),
            new Tag("Nintendo Switch", List.of(categoryRepository.findByName("Gaming").get())),
            new Tag("Nintendo Wii U", List.of(categoryRepository.findByName("Gaming").get())),
            new Tag("Nintendo Wii", List.of(categoryRepository.findByName("Gaming").get())),
            new Tag("Nintendo GameCube", List.of(categoryRepository.findByName("Gaming").get())),
            new Tag("Nintendo 64", List.of(categoryRepository.findByName("Gaming").get())),
            new Tag("Nintendo 3DS", List.of(categoryRepository.findByName("Gaming").get())),
            new Tag("Nintendo DS", List.of(categoryRepository.findByName("Gaming").get())),
            new Tag("Nintendo DSi", List.of(categoryRepository.findByName("Gaming").get())),
            new Tag("Nintendo GameBoy Advance", List.of(categoryRepository.findByName("Gaming").get())),
            new Tag("Nintendo GameBoy Color", List.of(categoryRepository.findByName("Gaming").get())),
            new Tag("Nintendo GameBoy", List.of(categoryRepository.findByName("Gaming").get())),
            new Tag("PC", List.of(categoryRepository.findByName("Gaming").get(), categoryRepository.findByName("Technology").get(), categoryRepository.findByName("Internet").get(), categoryRepository.findByName("Business").get())),
            new Tag("Mac", List.of(categoryRepository.findByName("Gaming").get(), categoryRepository.findByName("Technology").get())),
            new Tag("Linux", List.of(categoryRepository.findByName("Gaming").get(), categoryRepository.findByName("Technology").get())),
            new Tag("Android", List.of(categoryRepository.findByName("Gaming").get(), categoryRepository.findByName("Technology").get())),
            new Tag("iOS", List.of(categoryRepository.findByName("Gaming").get(), categoryRepository.findByName("Technology").get())),
            new Tag("PlayStation", List.of(categoryRepository.findByName("Gaming").get(), categoryRepository.findByName("Technology").get(), categoryRepository.findByName("Industry").get())),
            new Tag("Xbox", List.of(categoryRepository.findByName("Gaming").get(), categoryRepository.findByName("Technology").get(), categoryRepository.findByName("Industry").get())),
            new Tag("Nintendo", List.of(categoryRepository.findByName("Gaming").get(), categoryRepository.findByName("Technology").get(), categoryRepository.findByName("Industry").get())),
            new Tag("Steam", List.of(categoryRepository.findByName("Gaming").get(), categoryRepository.findByName("Technology").get(), categoryRepository.findByName("Industry").get())),
            new Tag("Epic Games", List.of(categoryRepository.findByName("Gaming").get(), categoryRepository.findByName("Technology").get(), categoryRepository.findByName("Industry").get())),
            new Tag("EA", List.of(categoryRepository.findByName("Gaming").get(), categoryRepository.findByName("Technology").get(), categoryRepository.findByName("Industry").get())),
            new Tag("Ubisoft", List.of(categoryRepository.findByName("Gaming").get(), categoryRepository.findByName("Technology").get(), categoryRepository.findByName("Industry").get())),
            new Tag("Activision", List.of(categoryRepository.findByName("Gaming").get(), categoryRepository.findByName("Technology").get(), categoryRepository.findByName("Industry").get())),
            new Tag("Rockstar Games", List.of(categoryRepository.findByName("Gaming").get(), categoryRepository.findByName("Technology").get(), categoryRepository.findByName("Industry").get())),
            new Tag("Bethesda", List.of(categoryRepository.findByName("Gaming").get(), categoryRepository.findByName("Technology").get(), categoryRepository.findByName("Industry").get())),
            new Tag("Blizzard", List.of(categoryRepository.findByName("Gaming").get(), categoryRepository.findByName("Technology").get(), categoryRepository.findByName("Industry").get())),
            new Tag("GTA", List.of(categoryRepository.findByName("Gaming").get())),
            new Tag("Call of Duty", List.of(categoryRepository.findByName("Gaming").get())),
            new Tag("FIFA", List.of(categoryRepository.findByName("Gaming").get(), categoryRepository.findByName("Sport").get())),
            new Tag("Minecraft", List.of(categoryRepository.findByName("Gaming").get())),
            new Tag("Fortnite", List.of(categoryRepository.findByName("Gaming").get())),
            new Tag("League of Legends", List.of(categoryRepository.findByName("Gaming").get())),
            new Tag("World of Warcraft", List.of(categoryRepository.findByName("Gaming").get())),
            new Tag("Overwatch", List.of(categoryRepository.findByName("Gaming").get())),
            new Tag("Valorant", List.of(categoryRepository.findByName("Gaming").get())),
            new Tag("Apex Legends", List.of(categoryRepository.findByName("Gaming").get())),
            new Tag("Counter-Strike", List.of(categoryRepository.findByName("Gaming").get())),
            new Tag("Dota 2", List.of(categoryRepository.findByName("Gaming").get())),
            new Tag("Rocket League", List.of(categoryRepository.findByName("Gaming").get())),
            new Tag("Survival Horror", List.of(categoryRepository.findByName("Gaming").get())),
            new Tag("Action", List.of(categoryRepository.findByName("Gaming").get(), categoryRepository.findByName("Cinema").get(), categoryRepository.findByName("TV").get())),
            new Tag("Adventure", List.of(categoryRepository.findByName("Gaming").get(), categoryRepository.findByName("Cinema").get())),
            new Tag("Simulation", List.of(categoryRepository.findByName("Gaming").get(), categoryRepository.findByName("Cinema").get())),
            new Tag("Strategy", List.of(categoryRepository.findByName("Gaming").get())),
            new Tag("RPG", List.of(categoryRepository.findByName("Gaming").get())),
            new Tag("MMORPG", List.of(categoryRepository.findByName("Gaming").get())),
            new Tag("Racing", List.of(categoryRepository.findByName("Gaming").get())),
            new Tag("Sports", List.of(categoryRepository.findByName("Gaming").get())),
            new Tag("Puzzle", List.of(categoryRepository.findByName("Gaming").get())),
            new Tag("Platformer", List.of(categoryRepository.findByName("Gaming").get())),
            new Tag("Fighting", List.of(categoryRepository.findByName("Gaming").get())),
            new Tag("Shooter", List.of(categoryRepository.findByName("Gaming").get())),
            new Tag("Battle Royale", List.of(categoryRepository.findByName("Gaming").get())),
            new Tag("Rhythm", List.of(categoryRepository.findByName("Gaming").get())),
            new Tag("Stealth", List.of(categoryRepository.findByName("Gaming").get())),
            new Tag("Survival", List.of(categoryRepository.findByName("Gaming").get())),
            new Tag("Horror", List.of(categoryRepository.findByName("Gaming").get(), categoryRepository.findByName("Cinema").get())),
            new Tag("Comedy", List.of(categoryRepository.findByName("Cinema").get(), categoryRepository.findByName("TV").get())),
            new Tag("Drama", List.of(categoryRepository.findByName("Cinema").get(), categoryRepository.findByName("TV").get())),
            new Tag("Thriller", List.of(categoryRepository.findByName("Cinema").get(), categoryRepository.findByName("TV").get())),
            new Tag("Sci-fi", List.of(categoryRepository.findByName("Cinema").get(), categoryRepository.findByName("TV").get())),
            new Tag("Fantasy", List.of(categoryRepository.findByName("Cinema").get(), categoryRepository.findByName("TV").get())),
            new Tag("Romance", List.of(categoryRepository.findByName("Cinema").get(), categoryRepository.findByName("TV").get())),
            new Tag("Mystery", List.of(categoryRepository.findByName("Cinema").get(), categoryRepository.findByName("TV").get())),
            new Tag("Crime", List.of(categoryRepository.findByName("Cinema").get(), categoryRepository.findByName("TV").get())),
            new Tag("Animation", List.of(categoryRepository.findByName("Cinema").get(), categoryRepository.findByName("TV").get())),
            new Tag("Documentary", List.of(categoryRepository.findByName("Cinema").get(), categoryRepository.findByName("TV").get())),
            new Tag("Reality TV", List.of(categoryRepository.findByName("TV").get())),
            new Tag("Talk Show", List.of(categoryRepository.findByName("TV").get())),
            new Tag("Sitcom", List.of(categoryRepository.findByName("TV").get())),
            new Tag("BMW", List.of(categoryRepository.findByName("Automotive").get(), categoryRepository.findByName("Industry").get(), categoryRepository.findByName("Technology").get())),
            new Tag("Mercedes-Benz", List.of(categoryRepository.findByName("Automotive").get(), categoryRepository.findByName("Industry").get(), categoryRepository.findByName("Technology").get())),
            new Tag("Volkswagen", List.of(categoryRepository.findByName("Automotive").get(), categoryRepository.findByName("Industry").get(), categoryRepository.findByName("Technology").get())),
            new Tag("Porsche", List.of(categoryRepository.findByName("Automotive").get(), categoryRepository.findByName("Industry").get(), categoryRepository.findByName("Technology").get())),
            new Tag("Audi", List.of(categoryRepository.findByName("Automotive").get(), categoryRepository.findByName("Industry").get(), categoryRepository.findByName("Technology").get())),
            new Tag("Ferrari", List.of(categoryRepository.findByName("Automotive").get(), categoryRepository.findByName("Industry").get(), categoryRepository.findByName("Technology").get())),
            new Tag("Lamborghini", List.of(categoryRepository.findByName("Automotive").get(), categoryRepository.findByName("Industry").get(), categoryRepository.findByName("Technology").get())),
            new Tag("Alfa Romeo", List.of(categoryRepository.findByName("Automotive").get(), categoryRepository.findByName("Industry").get(), categoryRepository.findByName("Technology").get())),
            new Tag("Maserati", List.of(categoryRepository.findByName("Automotive").get(), categoryRepository.findByName("Industry").get(), categoryRepository.findByName("Technology").get())),
            new Tag("Bugatti", List.of(categoryRepository.findByName("Automotive").get(), categoryRepository.findByName("Industry").get(), categoryRepository.findByName("Technology").get())),
            new Tag("Koenigsegg", List.of(categoryRepository.findByName("Automotive").get(), categoryRepository.findByName("Industry").get(), categoryRepository.findByName("Technology").get())),
            new Tag("Aston Martin", List.of(categoryRepository.findByName("Automotive").get(), categoryRepository.findByName("Industry").get(), categoryRepository.findByName("Technology").get())),
            new Tag("Italy", List.of(categoryRepository.findByName("Travel").get())),
            new Tag("France", List.of(categoryRepository.findByName("Travel").get())),
            new Tag("Spain", List.of(categoryRepository.findByName("Travel").get())),
            new Tag("Germany", List.of(categoryRepository.findByName("Travel").get())),
            new Tag("United Kingdom", List.of(categoryRepository.findByName("Travel").get())),
            new Tag("United States", List.of(categoryRepository.findByName("Travel").get())),
            new Tag("China", List.of(categoryRepository.findByName("Travel").get())),
            new Tag("Japan", List.of(categoryRepository.findByName("Travel").get())),
            new Tag("Russia", List.of(categoryRepository.findByName("Travel").get())),
            new Tag("Turkey", List.of(categoryRepository.findByName("Travel").get())),
            new Tag("Football", List.of(categoryRepository.findByName("Sport").get(), categoryRepository.findByName("Gaming").get())),
            new Tag("Basketball", List.of(categoryRepository.findByName("Sport").get(), categoryRepository.findByName("Gaming").get())),
            new Tag("Tennis", List.of(categoryRepository.findByName("Sport").get(), categoryRepository.findByName("Gaming").get())),
            new Tag("Volleyball", List.of(categoryRepository.findByName("Sport").get(), categoryRepository.findByName("Gaming").get())),
            new Tag("Baseball", List.of(categoryRepository.findByName("Sport").get(), categoryRepository.findByName("Gaming").get())),
            new Tag("Golf", List.of(categoryRepository.findByName("Sport").get(), categoryRepository.findByName("Gaming").get())),
            new Tag("Ice Hockey", List.of(categoryRepository.findByName("Sport").get(), categoryRepository.findByName("Gaming").get())),
            new Tag("Rugby", List.of(categoryRepository.findByName("Sport").get(), categoryRepository.findByName("Gaming").get())),
            new Tag("Cricket", List.of(categoryRepository.findByName("Sport").get(), categoryRepository.findByName("Gaming").get())),
            new Tag("Boxing", List.of(categoryRepository.findByName("Sport").get(), categoryRepository.findByName("Gaming").get())),
            new Tag("MMA", List.of(categoryRepository.findByName("Sport").get(), categoryRepository.findByName("Gaming").get())),
            new Tag("Wrestling", List.of(categoryRepository.findByName("Sport").get(), categoryRepository.findByName("Gaming").get())),
            new Tag("Athletics", List.of(categoryRepository.findByName("Sport").get())),
            new Tag("Swimming", List.of(categoryRepository.findByName("Sport").get())),
            new Tag("Cycling", List.of(categoryRepository.findByName("Sport").get())),
            new Tag("Skiing", List.of(categoryRepository.findByName("Sport").get())),
            new Tag("Snowboarding", List.of(categoryRepository.findByName("Sport").get())),
            new Tag("Surfing", List.of(categoryRepository.findByName("Sport").get())),
            new Tag("Skateboarding", List.of(categoryRepository.findByName("Sport").get())),
            new Tag("Motorsport", List.of(categoryRepository.findByName("Sport").get())),
            new Tag("Gymnastics", List.of(categoryRepository.findByName("Sport").get())),
            new Tag("Pie", List.of(categoryRepository.findByName("Food").get())),
            new Tag("Cake", List.of(categoryRepository.findByName("Food").get())),
            new Tag("Cookie", List.of(categoryRepository.findByName("Food").get())),
            new Tag("Ice Cream", List.of(categoryRepository.findByName("Food").get())),
            new Tag("Chocolate", List.of(categoryRepository.findByName("Food").get())),
            new Tag("Candy", List.of(categoryRepository.findByName("Food").get())),
            new Tag("Burger", List.of(categoryRepository.findByName("Food").get())),
            new Tag("Pizza", List.of(categoryRepository.findByName("Food").get())),
            new Tag("Pasta", List.of(categoryRepository.findByName("Food").get())),
            new Tag("Salad", List.of(categoryRepository.findByName("Food").get())),
            new Tag("Sandwich", List.of(categoryRepository.findByName("Food").get())),
            new Tag("Soup", List.of(categoryRepository.findByName("Food").get())),
            new Tag("Sushi", List.of(categoryRepository.findByName("Food").get())),
            new Tag("Steak", List.of(categoryRepository.findByName("Food").get())),
            new Tag("Fish", List.of(categoryRepository.findByName("Food").get())),
            new Tag("Chicken", List.of(categoryRepository.findByName("Food").get())),
            new Tag("Pork", List.of(categoryRepository.findByName("Food").get())),
            new Tag("Beef", List.of(categoryRepository.findByName("Food").get())),
            new Tag("Lamb", List.of(categoryRepository.findByName("Food").get())),
            new Tag("Duck", List.of(categoryRepository.findByName("Food").get())),
            new Tag("Goose", List.of(categoryRepository.findByName("Food").get())),
            new Tag("Rabbit", List.of(categoryRepository.findByName("Food").get())),
            new Tag("Vegetables", List.of(categoryRepository.findByName("Food").get())),
            new Tag("Fruit", List.of(categoryRepository.findByName("Food").get())),
            new Tag("Nuts", List.of(categoryRepository.findByName("Food").get())),
            new Tag("Bonsai", List.of(categoryRepository.findByName("Nature").get())),
            new Tag("Flowers", List.of(categoryRepository.findByName("Nature").get())),
            new Tag("Trees", List.of(categoryRepository.findByName("Nature").get())),
            new Tag("Birds", List.of(categoryRepository.findByName("Nature").get())),
            new Tag("Insects", List.of(categoryRepository.findByName("Nature").get())),
            new Tag("Reptiles", List.of(categoryRepository.findByName("Nature").get())),
            new Tag("Amphibians", List.of(categoryRepository.findByName("Nature").get())),
            new Tag("Mammals", List.of(categoryRepository.findByName("Nature").get())),
            new Tag("Dinosaurs", List.of(categoryRepository.findByName("Nature").get())),
            new Tag("Pluto", List.of(categoryRepository.findByName("Science").get())),
            new Tag("Mars", List.of(categoryRepository.findByName("Science").get())),
            new Tag("Jupiter", List.of(categoryRepository.findByName("Science").get())),
            new Tag("Saturn", List.of(categoryRepository.findByName("Science").get())),
            new Tag("Uranus", List.of(categoryRepository.findByName("Science").get())),
            new Tag("Neptune", List.of(categoryRepository.findByName("Science").get())),
            new Tag("Mercury", List.of(categoryRepository.findByName("Science").get())),
            new Tag("Venus", List.of(categoryRepository.findByName("Science").get())),
            new Tag("Earth", List.of(categoryRepository.findByName("Science").get())),
            new Tag("Sun", List.of(categoryRepository.findByName("Science").get())),
            new Tag("Moon", List.of(categoryRepository.findByName("Science").get()))
        );
        tags.forEach(tag -> {
            tag.setCreatedBy(1L);
            tag.setUpdatedBy(1L);
        });
        tagRepository.saveAll(tags);
    }
}
